<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>x86;AnyCPU</Platforms>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>    
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <NoWarn>1701;1702;CS3021</NoWarn>
    <DefineConstants>TRACE</DefineConstants>
	<PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <DefineConstants>TRACE;DEBUG</DefineConstants>
	<PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;CS3021</NoWarn>
    <DefineConstants>TRACE</DefineConstants>
	<PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE;DEBUG</DefineConstants>
	<PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sound" />
  </ItemGroup>

  <!--
  <ItemGroup>
    <Reference Include="Sound">
      <HintPath>..\..\..\Sound\bin\Debug\net462\Sound.dll</HintPath>
    </Reference>
  </ItemGroup>
  -->
  
</Project>
